module.exports = {
  VARIABLE_VALUE: "VARIABLE VALUE", // 6
  VARIABLE_OBJECT: "VARIABLE OBJECT", // 7
  VARIABLE_ARRAY: "VARIABLE ARRAY", // 8
  VARIABLE_FUNCTION_EXE: "VARIABLE FUNCTION EXE", // 9
  VARIABLE_VARIABLE: "VARIABLE VARIABLE", // 10
  VARIABLE_EXPRESSION: "VARIABLE EXPRESSION", // 10
  VARIABLE_VARIABLE_ARRAY_ELEMENT: "VARIABLE VARIABLE ARRAY ELEMENT", // 12
  ANONYMOUS_VARIABLE: "ANONYMOUS VARIABLE", // 11
  ANONYMOUS_VALUE: "ANONYMOUS VALUE", // 12
  ANONYMOUS_FUNCTION_EXE: "ANONYMOUS FUNCTION EXE", // 12
  ANONYMOUS_VARIABLE_ARRAY_ELEMENT: "ANONYMOUS VARIABLE ARRAY ELEMENT", // 12
  ANONYMOUS_OBJECT: "ANONYMOUS OBJECT", // 12
  ANONYMOUS_ARRAY: "ANONYMOUS ARRAY", // 12
  ANONYMOUS_EXPRESSION: "ANONYMOUS EXPRESSION", // 10
  ANONYMOUS_CALLBACK: "ANONYMOUS CALLBACK", // 10
  RETURN_VALUE: "RETURN VALUE", // 13
  RETURN_VARIABLE: "RETURN VARIABLE", // 14
  RETURN_OBJECT: "RETURN OBJECT", // 15
  RETURN_ARRAY: "RETURN ARRAY", // 16
  RETURN_ARRAY_ELEMENT: "RETURN ARRAY ELEMENT", // 12
  RETURN_FUNCTIONEXE: "RETURN FUNCTIONEXE", // 17
  FUNCTION_EXE: "FUNCTION EXE", // 18
  FUNCTION_DECLARATION: "FUNCTION DECLARATION", // 19
  IF_STATEMENT: "IF STATEMENT", // 20
  FOR_STATEMENT: "FOR STATEMENT", // 21
  IMPORT: "IMPORT", // 22
  ERROR: "ERROR", // 23
  UNKNOW: "UNKNOW" // 24
}